### PR TITLE
travis: use ccache

### PR DESCRIPTION
**Pull request by miri64**
I'm not sure this works with Docker, but let's give it a try ;-)

### CODE REVIEW

**Comment by miri64** [comment]
(not sure why I can't select @cladmi for this...)

**Comment by kaspar030** [comment]
now 5 min, before it was 4...

**Comment by miri64** [comment]
> now 5 min, before it was 4...

With that amount of cache misses this isn't surprising. Should I hit rebuild?

**Comment by miri64** [comment]
Mhhhh. I think the results cache entries go to the *docker*'s `$HOME/.ccache`, as the cache grabbed by Travis seems to be empty :-/

image

**Comment by miri64** [comment]
Maybe let's wait for @cladmi to return from his vacation before we merge this ;-)

**Comment by miri64** [comment]
(or dismiss it)

**Comment by cladmi** [comment]
There is indeed a limitation that https://github.com/RIOT-OS/RIOT/blob/59b4dcffed6b8f32e6fba01e262e941d7413f7ca/makefiles/docker.inc.mk currently does not map 'CCACHE_DIR' directory or exports the 'CCACHE' variable to the docker container.

You can see it in the build output that no mapping is done for it:

https://travis-ci.com/RIOT-OS/Tutorials/jobs/192912816#L476-L494
(`CC=gcc` is passed to docker, fortunately we have `CC =  $(PREFIX)gcc` without at `?=`)

Also, for `travis` it looks like it is using the `${HOME}/.casher` as a ccache (or cache base ?) directory:

https://travis-ci.com/RIOT-OS/Tutorials/jobs/192912816#L451-L456

So would need additional configuration.

**Comment by miri64** [comment]
> Also, for `travis` it looks like it is using the `${HOME}/.casher` as a ccache (or cache base ?) directory:
> 
> https://travis-ci.com/RIOT-OS/Tutorials/jobs/192912816#L451-L456

It does not look to me like that. The variable you are referring to is called `CASHER_DIR`. From that I'm not sure it is the output of `ccache` necessarily. Maybe it is just were the produced cache tar is stored for pick-up?

**Comment by miri64** [comment]
Yupp, [according to the doc](https://docs.travis-ci.com/user/caching/#ccache-cache) the `ccache` output shoulds till go to `$HOME/.ccache`.

**Comment by cladmi** [comment]
> Yupp, [according to the doc](https://docs.travis-ci.com/user/caching/#ccache-cache) the `ccache` output shoulds till go to `$HOME/.ccache`.

Ok thanks for checking.

**Comment by miri64** [comment]
Since the new Github actions are using the Docker image (which uses ccache), we can close this one.

**Pull request closed without merging**
