### PR TITLE
travis: initial import of simple build job

### PR DESCRIPTION
**Pull request by miri64**
This prevents our tutorials from degrading too much ;-).

Requires #58.

### CODE REVIEW

**Comment by miri64** [comment]
(I separate the RIOT update out into its own commit once I get a successful build ;-))

**Comment by miri64** [comment]
Rebased and squashed to current master as #58 was merged

**Comment by kaspar030** [comment]
LGTM.

**Comment by kaspar030** [comment]
Should we set successful travis to be mandatory?

**Comment by miri64** [comment]
Yepp. That was my idea :-)

**Pull request merged**
