### PR TITLE
Provide Github Action workflow to compile test the tasks

### PR DESCRIPTION
**Pull request by miri64**
This ports the compile tests currently done with Travis to a GitHub Action.

See https://github.com/RIOT-OS/Tutorials/pull/78#issuecomment-768284665.

### CODE REVIEW

**Comment by miri64** [comment]
Rebased to current master.

**Comment by Teufelchen1** [comment]
What do we need to get this merged?

**Comment by miri64** [comment]
Let me check what the issue with native was.

**Comment by miri64** [comment]
(it might be just that we need a bump to the most current release ... and removing the travis requirement for merge of course)

**Comment by miri64** [comment]
> (it might be just that we need a bump to the most current release

Yepp, that fixed it.

**Review by benpicco — APPROVED** [review]

**Pull request merged**
