### PR TITLE
RIOT: update to 2022.07

### PR DESCRIPTION
**Pull request by OlegHahm**
The current version won't even compile.

### CODE REVIEW

**Review by miri64 — APPROVED** [review]
I guess you tested this?

**Comment by OlegHahm** [comment]
To be honest: only task-01. But I will do for the rest as well during next week.

**Comment by miri64** [comment]
Maybe https://github.com/RIOT-OS/Tutorials/pull/79 would help with that (and also this PR would help that PR it could build). Travis seems to have given up on building our stuff...

**Comment by miri64** [comment]
Was bumped to 2023.10 in https://github.com/RIOT-OS/Tutorials/pull/79

**Pull request closed without merging**
